DTStack/dt-sql-parser

src/utils/index.ts
test/utils/index.test.ts

fix: clean sql white spaces

---

src/utils/index.ts
test/utils/index.test.ts

Reverts DTStack/dt-sql-parser#26

Revert "fix: clean sql white spaces"

---

src/utils/index.ts
test/utils/index.test.ts

fix: lexer for comment

---

package.json
src/parser/flinksql.ts
src/parser/generic.ts
src/parser/hive.ts
src/parser/plsql.ts
src/parser/spark.ts
tsconfig.json

build: add the basic type declaration

---

src/utils/index.ts
test/utils/index.test.ts

issue: #46 
修复 sqlsplit 嵌套括号匹配出错为题

fix: fix bracket match

---

README-zh_CN.md
README.md
test/parser/flinksql/lexer.test.ts

- 增加 TrinoSQL 文档
- 修复 https://github.com/DTStack/dt-sql-parser/issues/79

docs(generic): fix documentation error

---

test/parser/hive/syntax/fixtures/alterTable.sql
test/parser/hive/syntax/fixtures/describe.sql
test/parser/hive/syntax/fixtures/load.sql
test/parser/hive/syntax/fixtures/select.sql
test/parser/hive/syntax/selectStatement.test.ts

#144 
- 新增SELECT的SQL语句以及单测，校验相关语法
- 修改ALTER TABLE的SQL语句，校验date日期数据类型
- 修改DESCRIBE的SQL语句，校验date日期数据类型
- 修改LOAD的SQL语句，校验date日期数据类型

test: add select sql and improve describe/load/alterTable's sql

---

scripts/antlr4.js

1. 将 `fs.rmdirSync` 替换为 `fs.rmSync`, 因为`fs.rmdirSync`  将在未来被弃用
2. format via prettier

build: replace rmdirSync with rmSync

---

src/utils/findCaretTokenIndex.ts

fix: correct import path of CaretPosition

---

src/grammar/flinksql/FlinkSqlParser.g4

[优化] flinksql parser grammar 中的字符串匹配模式都替换为 lexer rule

refactor: replace string pattern with lexer rule

---

package.json

在 packages.json 中添加 `sideEffects ` 字段，以触发webpack 的 treeShaking
[webpack treeshaking doc](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free)
在只应用了 flinksql 的情况下，加载了所有类型的sql parser

feat: add sideEffects field to trigger treeShaking

---

package.json
pnpm-lock.yaml
yarn.lock

feat: upgrade antlr4-c3 and fix the version

---

scripts/antlr4.js

修复 `lib/*` 文件夹不存在时，antlr4 命令报错的问题

build: fix antlr4 script

---

src/parser/common/basic-parser-types.ts

add column type to SyntaxContextType #211

feat: add column to syntaxContextType

---

src/index.ts
src/utils/index.ts
src/utils/token.ts
test/utils/index.test.ts

feat: deprecate legacy util

---

src/parser/common/basicParser.ts
src/parser/flinksql.ts
src/parser/hive.ts
src/parser/impala.ts
src/parser/mysql.ts
src/parser/pgsql.ts
src/parser/plsql.ts
src/parser/spark.ts
src/parser/trinosql.ts

update createLexerFormCharStream to createLexerFromCharStream

fix: rename createLexerFormCharStream to createLexerFromCharStream

---

README-zh_CN.md
README.md

docs: update readme.md

---

src/parser/trino/trinoErrorListener.ts
test/parser/mysql/contextCollect/entityCollector.test.ts
test/parser/postgresql/contextCollect/entityCollector.test.ts

ci: check-types and test unit update

---

src/index.ts

fix: #371 export EntityContext types

---

src/lib/flink/FlinkSqlParser.interp
src/lib/flink/FlinkSqlParser.ts
src/lib/flink/FlinkSqlParserListener.ts
src/lib/flink/FlinkSqlParserVisitor.ts

fix: #381 antlr4 flink grammar

---

scripts/antlr4.js

1. #351 
2. 过滤方法和 [`benchmark.js`](https://github.com/DTStack/dt-sql-parser/blob/main/scripts/benchmark.js#L10) 中保持一致

fix: #351 antlr4 command optimize
